<?xml version="1.0" encoding="UTF-8"?>
<!--
Generate Web Profile + Platform TCK signature map files for the following:
jakarta.annotation.sig
jakarta.batch.sig
jakarta.decorator.sig
jakarta.ejb.sig
jakarta.el.sig
jakarta.enterprise.concurrent.sig
jakarta.enterprise.sig (CDI)
jakarta.faces.sig
jakarta.inject.sig
jakarta.interceptor.sig
jakarta.jms.sig
jakarta.json.bind.sig
jakarta.json.sig (JSON-P)
jakarta.mail.sig
jakarta.persistence.sig
jakarta.resource.sig
jakarta.security.auth.message.sig
jakarta.security.enterprise.sig
jakarta.security.jacc.sig
jakarta.servlet.jsp.jstl.sig (Tags)
jakarta.servlet.jsp.sig
jakarta.servlet.sig
jakarta.transaction.sig
jakarta.validation.sig
jakarta.websocket.sig
jakarta.ws.rs.sig
javax.rmi.sig (Corba classes for EJB)
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>jakarta.tck</groupId>
        <artifactId>project</artifactId>
        <version>11.0.0-SNAPSHOT</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>

    <artifactId>generate</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.sigtest-maven-plugin>2.4</version.sigtest-maven-plugin>
    </properties>

    <dependencies>

        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>11.0.0-M4</version>
        </dependency>

        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-web-api</artifactId>
            <version>11.0.0-M4</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>

                <configuration>
                    <finalName></finalName>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>jakarta.annotation</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta.annotation.sig</sigfile>
                            <release>17</release>
                            <packages>jakarta.annotation</packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>jakarta.security.jacc</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta.security.jacc.sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.security.jacc
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.batch</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta.batch.sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.batch
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.ejb</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta.ejb.sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.ejb
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.el</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta.el.sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.el
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.concurrency</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta.enterprise.concurrency.sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.enterprise.concurrent
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.concurrency</id>
            <!--
            includes jakarta.decorator and jakarta.enterprise but exclude jakarta.enterprise.concurrent
            -->
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta.cdi.sig</sigfile>
                            <release>17</release>
                            <excludes>jakarta.enterprise.concurrent</excludes>
                            <packages>
                                jakarta.enterprise, jakarta.decorator
                            </packages>

                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.faces</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta.faces.sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.faces
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>jakarta.</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>jakarta.tck</groupId>
                        <artifactId>sigtest-maven-plugin</artifactId>
                        <version>${version.sigtest-maven-plugin}</version>

                        <configuration>
                            <sigfile>jakarta..sig</sigfile>
                            <release>17</release>
                            <packages>
                                jakarta.inject,
                                jakarta.interceptor,
                                jakarta.jms,
                                jakarta.json.bind,
                                jakarta.json,
                                jakarta.persistence,
                                jakarta.resource,
                                jakarta.security.enterprise,
                                jakarta.security.auth.message,
                                jakarta.servlet.jsp,
                                jakarta.servlet.jsp.jstl,
                                jakarta.transaction,
                                jakarta.validation,
                                jakarta.websocket,
                                jakarta.ws.rs,
                            </packages>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

</project>
